# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [0]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
url = 'https://raw.githubusercontent.com/talithakayla/ann/master/Churn_Modelling.csv'
dataset = pd.read_csv(url)
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
print(X)
print('')
print('Size X           : ', X.shape)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

Size X           :  (10000, 10)


In [0]:
print(y)
print('')
print('Size y           : ', y.shape)

[1 0 1 ... 1 1 0]

Size y           :  (10000,)


### Encoding categorical data

Label Encoding the "Gender" column

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [0]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [0]:
print(X)
print('Size X           : ', X.shape)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
Size X           :  (10000, 12)


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

1.   List item
2.   List item



### Compiling the ANN

In [0]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [0]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6302 - accuracy: 0.6940
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4654 - accuracy: 0.8016
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4365 - accuracy: 0.8086
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4225 - accuracy: 0.8183
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4094 - accuracy: 0.8280
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3969 - accuracy: 0.8366
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3855 - accuracy: 0.8445
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3755 - accuracy: 0.8482
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3666 - accuracy: 0.8500
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3598 - accura

## Part 4 - Predicting The Result

In [0]:
#homework

result = ann.predict(sc.transform([[1, 0 , 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
print('So, should we say goodbye to that customer is ',result)

So, should we say goodbye to that customer is  [[0.02588217]]


In [0]:
result = ann.predict(sc.transform([[1, 0 , 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5
print('So, should we say goodbye to that customer is ',result)

So, should we say goodbye to that customer is  [[False]]


### Predictiong The Test set result

In [0]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) 
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making The Confusion Matrix

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1502   93]
 [ 185  220]]


0.861